[config]
default_to_workspace = false

[env.development]
BUILD_PROFILE_TEXT = "dev"
DEBUG_OR_RELEASE_TEXT = "debug"

[env.production]
BUILD_PROFILE_TEXT = "release"
DEBUG_OR_RELEASE_TEXT = "release"

[tasks.echo]
script_runner = "@shell"
script = ['''
echo COMMON: ${COMMON}
echo PROFILE_NAME: ${PROFILE_NAME}
echo IS_DEV: ${IS_DEV}
echo IS_PROD: ${IS_PROD}
''']

[tasks.build]
dependencies = ["build_match_copy_artifacts"]
command = "cargo"
args = ["build", "--profile", "${BUILD_PROFILE_TEXT}"]

[tasks.client]
command = "cargo"
args = ["run", "-p", "wrts", "--profile", "${BUILD_PROFILE_TEXT}"]

[tasks.server]
dependencies = ["build_server"]
command = "target/${DEBUG_OR_RELEASE_TEXT}/wrts_lobby.exe"

[tasks.build_server]
dependencies = ["build_match_copy_artifacts"]
command = "cargo"
args = ["build", "-p", "wrts_lobby", "--profile", "${BUILD_PROFILE_TEXT}"]

[tasks.build_match_copy_artifacts]
dependencies = ["build_match"]
script_runner = "@shell"
script = '''
mkdir wrts_lobby/build_assets/
cp target/${DEBUG_OR_RELEASE_TEXT}/wrts_match.exe wrts_lobby/build_assets/wrts_match.exe
'''

[tasks.build_match]
command = "cargo"
args = ["build", "-p", "wrts_match", "--profile", "${BUILD_PROFILE_TEXT}"]
