[package]
name = "wrts_match_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
slotmap = "1.0.7"
glam = { version = "0.29.3", features = ["serde"] }
paste = "1.0.15"
splines = { version = "5.0.0", features = ["glam"] }
